# Generated by Django 2.1.1 on 2018-10-26 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegebettingpoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_risk_game', models.CharField(max_length=200)),
                ('participant_username', models.CharField(max_length=200)),
                ('week', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game_of_the_Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1', models.CharField(max_length=200)),
                ('team_2', models.CharField(max_length=200)),
                ('total_points_scored', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_of_the_week',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='bettingsheet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegebettingpoolapp.Game'),
        ),
        migrations.AddField(
            model_name='bettingsheet',
            name='game_of_the_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegebettingpoolapp.Game_of_the_Week'),
        ),
    ]
