# Generated by Django 2.1.1 on 2018-10-28 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegebettingpoolapp', '0002_auto_20181026_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bettingsheet',
            name='participant_username',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_of_the_week',
        ),
        migrations.AddField(
            model_name='bettingsheet',
            name='total_points_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bettingsheet',
            name='game_of_the_week',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Game_of_the_Week',
        ),
        migrations.AddField(
            model_name='participant',
            name='betting_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegebettingpoolapp.BettingSheet'),
        ),
    ]
