# Generated by Django 2.1.2 on 2018-10-30 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegebettingpoolapp', '0004_auto_20181030_1711'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('userID', 'gameID')},
        ),
    ]
