# Generated by Django 2.1.2 on 2018-10-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegebettingpoolapp', '0006_auto_20181031_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
