# Generated by Django 2.1.2 on 2018-11-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegebettingpoolapp', '0013_auto_20181110_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='collegebettingpoolapp.Game'),
        ),
    ]
