# Generated by Django 2.1.2 on 2018-11-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegebettingpoolapp', '0014_bet_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegebettingpoolapp.Game'),
        ),
    ]
