language: python

env:
  - TOX_ENV=py2.6-django1.3
  - TOX_ENV=py2.6-django1.4
  - TOX_ENV=py2.6-django1.5

  - TOX_ENV=py2.7-django1.3
  - TOX_ENV=py2.7-django1.4
  - TOX_ENV=py2.7-django1.5
  - TOX_ENV=py2.7-django1.6
  - TOX_ENV=py2.7-django1.7
  - TOX_ENV=py2.7-django1.8
  - TOX_ENV=py2.7-django1.9

  - TOX_ENV=py3.4-django1.8
  - TOX_ENV=py3.4-django1.9

  - TOX_ENV=py3.5-django1.8
  - TOX_ENV=py3.5-django1.9

install:
  - pip install -U 'tox==2.2.1' 'pip<8.0.0' 'virtualenv<14.0.0'

script:
  - tox -e $TOX_ENV

notifications:
  email:
    recipients:
      - swistakm@gmail.com
    on_success: always
    on_failure: always
